version: '3.9'

services:
  db:
    image: alexmbarbosa/mysql5.7
    container_name: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_PORT: $MYSQL_PORT
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3366:3306

  adminer:
    image: adminer
    container_name: db_console
    restart: always
    environment:
      MYSQL_PORT: $MYSQL_PORT
    ports:
      - 8080:8080
    depends_on:
      - db
volumes:
  db_data: